#######################################################
# 
# ContrattoAcquisto.py
# Python implementation of the Class ContrattoAcquisto
# Generated by Enterprise Architect
# Created on:      08-ago-2025 16:25:20
# Original author: 39371
# 
#######################################################
import Contrattone

class ContrattoAcquisto(Contrattone):
    def aggiornaContratto():
        pass

    def creaContratto():
        pass

    def eliminaContratto():
        pass

    def ricercaContratto():
        pass

    def visualizzaContratto():
        pass