#######################################################
# 
# Fattura.py
# Python implementation of the Class Fattura
# Generated by Enterprise Architect
# Created on:      08-ago-2025 16:33:31
# Original author: 39371
# 
#######################################################


class Fattura:
    def creaFattura():
        pass

    def eliminaFattura():
        pass

    def ricercaFattura():
        pass

    def visualizzaFattura():
        pass